runtime: python39 # Usa python310 o python311 (no python312)

entrypoint: gunicorn -b 0.0.0.0:8080 app:app

# Ajusta si tu app está en otro archivo


handlers:
  - url: /static
    static_dir: static  # Sirve archivos estáticos desde la carpeta "static"

  - url: /.*
    script: auto  # Solo si estás en el entorno "Estándar" y sin usar `gunicorn`

automatic_scaling:
  max_instances: 50  # Ajusta este valor según tus necesidades

instance_class: F2  # Usa F2 o F4 si la carga es alta
